### ISSUE TITLE
how about change to http proxies?

### ISSUE THREAD

**Issue by ghost** [gingteam/ddoser#10]
how about making a http proxy tunnel using CONNECT method? so we don't need to use any 3rd proxy client and http proxies performance is better than socks4 too...
http dialer example using CONNECT method: https://github.com/rackerlabs/go-connect-tunnel/blob/master/proxy.go

**Comment by ghost** [comment]
Btw socks4 is very terrible if attacks website using https protocol

**Comment by ciricode** [comment]
> how about making a http proxy tunnel using CONNECT method? so we don't need to use any 3rd proxy client and http proxies performance is better than socks4 too... http dialer example using CONNECT method: https://github.com/rackerlabs/go-connect-tunnel/blob/master/proxy.go


I'm pretty busy at the moment, I'll try to check it out when I have time, any pull request is always welcome 🙏

**Comment by ging-dev** [comment]
@sussy-baka-imposter can you make PR for it?
